import { Provider } from './types';

export const PROVIDERS: Provider[] = [
  {
    id: 1,
    name: 'Dr. Elena Vance',
    title: 'EMDR Certified Psychologist',
    image: 'https://picsum.photos/id/64/200/200',
    availability: 'Tomorrow',
    vibe: 20,
    tags: ['CPTSD', 'Sexual Trauma', 'Attachment'],
    location: 'New York, NY',
    verified: true,
  },
  {
    id: 2,
    name: 'Marcus Thorne, LMFT',
    title: 'Trauma & Resilience Specialist',
    image: 'https://picsum.photos/id/91/200/200',
    availability: 'Mon, Oct 24',
    vibe: 80,
    tags: ['Panic Attacks', 'Grief', 'Veterans'],
    location: 'Chicago, IL',
    verified: true,
  },
  {
    id: 3,
    name: 'Sarah Jenkins',
    title: 'Somatic EMDR Therapist',
    image: 'https://picsum.photos/id/338/200/200',
    availability: 'Wed, Oct 26',
    vibe: 50,
    tags: ['Childhood Trauma', 'Anxiety', 'Body Work'],
    location: 'Austin, TX',
    verified: true,
  },
  {
    id: 4,
    name: 'Dr. Aris Chen, MD',
    title: 'Integrative Psychiatrist',
    image: 'https://picsum.photos/id/342/200/200',
    availability: 'Waiting List',
    vibe: 30,
    tags: ['Medication', 'PTSD', 'Sleep'],
    location: 'San Francisco, CA',
    verified: true,
  },
  {
      id: 5,
      name: 'Dr. Emily Carter',
      title: 'Clinical Psychologist',
      image: 'https://picsum.photos/id/349/200/200',
      availability: 'Tomorrow',
      vibe: 60,
      tags: ['Anxiety', 'Depression', 'Stress'],
      location: 'Los Angeles, CA',
      verified: true,
    },
    {
      id: 6,
      name: 'Michael Thompson',
      title: 'Licensed Counselor',
      image: 'https://picsum.photos/id/447/200/200',
      availability: 'Fri, Oct 28',
      vibe: 40,
      tags: ['Trauma', 'Grief', 'Relationship Issues'],
      location: 'Seattle, WA',
      verified: true,
    }
];
